# Generated by Django 4.1.2 on 2023-01-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adhar_number', models.CharField(max_length=12)),
                ('mobile_number', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('UID', models.TextField(max_length=100)),
            ],
        ),
    ]
