# Generated by Django 4.1.2 on 2023-01-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userregistartion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistartion',
            name='adhar_number',
            field=models.PositiveIntegerField(),
        ),
    ]
